### ISSUE TITLE
about inference time overhead

### ISSUE THREAD

**Issue by OuyangJunyuan** [Xharlie/BtcDet#1]
i d like to know if this model is enough effeciency or not. is it probably to run in real time? answer will be appreciated!

**Comment by Xharlie** [comment]
Thanks for raising the issue. The inference speed is similar to PVRCNN on my server. The overhead of occlusion learning could be improved by merging its backbone with detection pipeline, the improvement could be a good future direction.

**Comment by OuyangJunyuan** [comment]
> Thanks for raising the issue. The inference speed is similar to PVRCNN on my server. The overhead of occlusion learning could be improved by merging its backbone with detection pipeline, the improvement could be a good future direction.

thanks for your reply~
