### ISSUE TITLE
How to recover the shape miss according to the three types (EO, SM, SO) for producing the result of Figure 2 step by step?

### ISSUE THREAD

**Issue by jialeli1** [Xharlie/BtcDet#13]
Hi!

How to recover the shape miss according to the three types (EO, SM, SO) for producing the results of Figure 2 step by step?

Many thanks,
:)

**Comment by Xharlie** [comment]
You can follow the source / target shape matching and find closest objects which provide extra points in shape miss regions. Then,  you can classify the shape miss regions to 3 categories of EO, SM, SO . These extra points in EO is to recover EO, the extra points in SM is to recover SM.
