### ISSUE TITLE
About the visualization

### ISSUE THREAD

**Issue by Orbis36** [Xharlie/BtcDet#20]
Hi,
Could you tell me which tools you used to visualize the voxel?
I really love the style of your figure in the paper, but I can't find a library that allows the transparent visualization of voxels.(Occ in the paper)
Thanks for any help.

**Comment by Xharlie** [comment]
hi, i used mayavi.mlab   see https://github.com/open-mmlab/OpenPCDet/blob/master/tools/visual_utils/visualize_utils.py.
a voxel is actually meshes on the 8 faces.

**Comment by Orbis36** [comment]
Thanks!
