### ISSUE TITLE
COORD_TYPE: cylinder

### ISSUE THREAD

**Issue by Yzichen** [Xharlie/BtcDet#5]
Thanks for your open-source code!
Don’t we identify “shape missing" areas in a spherical coordinate system?  Why set COORD_TYPE = cylinder?

**Comment by Xharlie** [comment]
Hi Yzichen, the spherical coordinates cost more GPU memory, which i'm only able to run on better GPUs than 1080 ti. During code release, to accommodate the hardware facilities of broader audiences, I later implemented this community version which partitions the space by "cylinder" (the logic of occlusion is also adjusted a bit for cylinder) and which can get similar results, the difference is minimal and the memory space usage is much more efficient.

**Comment by Yzichen** [comment]
I get it, thanks for your reply ！
